apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-templates
  annotations:
    github.com/project-slug: kavyan256/backstage-templates
spec:
  type: other
  lifecycle: unknown
  owner: user:kavyan256
