apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-express-service
  title: Create Node.js/Express Service
  description: Scaffolds a new Node.js Express service with catalog and TechDocs
  tags:
    - nodejs
    - express
    - backend
spec:
  owner: user:kavyan256
  type: service

  parameters:
    - title: Service Info
      required: [serviceName, description, owner]
      properties:
        serviceName:
          type: string
          title: Service Name
          description: Lowercase, no spaces (e.g. my-api-service)
        description:
          type: string
          title: Short Description
        owner:
          type: string
          title: Owner (GitHub username)
          default: kavyan256
        port:
          type: string
          title: Port
          default: "3000"

    - title: Repository
      required: [repoUrl]
      properties:
        repoUrl:
          type: string
          title: Create New GitHub Repository
          description: Name the new repo to create
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]

  steps:
    - id: fetch
      name: Generate Files
      action: fetch:template
      input:
        url: ./skeleton
        values:
          serviceName: ${{ parameters.serviceName }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          port: ${{ parameters.port }}

    - id: publish
      name: Create GitHub Repo
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main
        repoVisibility: public

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: View Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: View in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}